### ISSUE TITLE
Importing Hoard of the Dragon Queen

### ISSUE THREAD

**Issue by ignatiuss** [VTTAssets/vtta-ddb#8] opened 2021-03-20 21:31 UTC
I am trying to import Hoard of the dragon queen. I can see this message in Chrome Dev Tools:

{ 
  message: "Not (yet) supported"
  success: false
}

![vtta-dndbeyond-error-import-hotdq](https://user-images.githubusercontent.com/232595/111886140-f6f7e000-89c3-11eb-981e-dde8bd4421b3.png)

**Comment by VTTAssets** [comment] 2021-03-21 08:57
Duplicate of #7

**Closed** 2021-03-21 08:58 UTC
Labels: duplicate
